services:
  api:
    build: .
    ports:
      - 80:80
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_APP=main
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
